### ISSUE TITLE
error after installing attest

### ISSUE THREAD

**Issue by ISM-APAC** [joshuamcclure/cypress-attest#6]
**Error: Cannot find module 'attest-reporter'**
```
Require stack:
- D:\Other Stuff\GenesisLab\Repos\VSTSCypressRepo\CypressTestAutomationFramework\node_modules\cypress-attest\tasks.js
- D:\Other Stuff\GenesisLab\Repos\VSTSCypressRepo\CypressTestAutomationFramework\cypress\plugins\index.js
- C:\Users\c.jayasinghe\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js
- C:\Users\c.jayasinghe\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\lib\plugins\child\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (D:\Other Stuff\GenesisLab\Repos\VSTSCypressRepo\CypressTestAutomationFramework\node_modules\cypress-attest\tasks.js:2:24)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (D:\Other Stuff\GenesisLab\Repos\VSTSCypressRepo\CypressTestAutomationFramework\cypress\plugins\index.js:27:22)
```

**Comment by joshuamcclure** [comment]
@ISM-APAC Thanks for reporting this issue. Deque's Attest packages are now in mono-repo, so I have updated the dependency definitions accordingly.

**Comment by abhas-kumar-singh** [comment]
I am still facing the issue with **Error: Cannot find module '@deque/attest-reporter'**. Opening a new issue with details. Please help me to fix this.
